# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=57679

// List all promo codes
GET {{host}}:{{port}}/PromoCodes

###

// Get a specific promo code
@id_to_get=1
GET {{host}}:{{port}}/PromoCodes/{{id_to_get}}

###

// Add a new promo code
POST {{host}}:{{port}}/PromoCodes
Content-Type: application/json

{
  "name": "Test promo code",
  "code": "PromoCode1",
  "maxPossibleDownloads": 10
}

###

// Update a promo code
@id_to_update=1
PUT {{host}}:{{port}}/PromoCodes/{{id_to_update}}
Content-Type: application/json

{
  "id": {{id_to_update}},
  "name": "newName"
}

###

// Delete a promo code
@id_to_delete=1
DELETE {{host}}:{{port}}/PromoCodes/{{id_to_delete}}

###

// Mark as inactive
@id_to_mark_as_invactive=1
PUT {{host}}:{{port}}/PromoCodes/{{id_to_mark_as_invactive}}/MarkAsInactive

